import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { clsx } from "clsx";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Section(props: {
  id: string;
  heading: ReactNode;
  children: ReactNode;
}) {
  const { id, heading, children } = props;
  return (
    <section
      id={id}
      className="mb-12 flex flex-col-reverse items-center justify-center gap-8 p-6 sm:flex-row"
    >
      <article className="sm:w-1/2">
        <h2 className="text-center text-4xl font-bold text-slate-900 sm:text-left sm:text-5xl dark:text-white">
          {heading}
        </h2>
        <p className="mt-4 max-w-md text-center text-2xl text-slate-700 sm:text-left dark:text-slate-400">
          {children}
        </p>
      </article>
      <img
        className="sm:w-1/2"
        src="/mentoring-logo.svg"
        style={{ color: "currentcolor" }}
      />
    </section>
  );
}

function Nav() {
  return (
    <nav className="hidden space-x-8 text-xl sm:block" aria-label="main">
      <a href="#mentoring" className="hover:opacity-90">
        Mentoring
      </a>
      <a href="#" className="hover:opacity-90">
        Development
      </a>
      <a href="#" className="hover:opacity-90">
        rocket
      </a>
      <a href="#" className="hover:opacity-90">
        rocket
      </a>
    </nav>
  );
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.className,
          "min-h-screen bg-slate-50 dark:bg-black dark:text-white",
        )}
      >
        <header className="sticky top-0 z-10 bg-teal-700 text-white">
          <section className="mx-auto flex max-w-4xl items-center justify-between p-4">
            <span className="text-3xl font-medium">stroiman</span>
            <div>
              <button
                id="mobile-open"
                className="text-3xl focus:outline-none sm:hidden"
              >
                &#9776;
              </button>
              <Nav />
            </div>
          </section>
        </header>

        <main className="mx-auto max-w-4xl">
          <Section
            id="mentoring"
            heading={
              <>
                Let'see where this{" "}
                <span className="text-indigo-700 dark:text-indigo-300">
                  leads us
                </span>
              </>
            }
          >
            This is going to be wild
          </Section>

          <hr className="mx-auto w-1/2 bg-black dark:bg-white" />

          {children}
        </main>
      </body>
    </html>
  );
}
