import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { clsx } from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Nav() {
  return (
    <nav className="hidden space-x-8 text-xl sm:block" aria-label="main">
      <a href="#mentoring" className="hover:opacity-90">
        Mentoring
      </a>
      <a href="#software-development" className="hover:opacity-90">
        Development
      </a>
      <a href="#" className="hover:opacity-90">
        rocket
      </a>
      <a href="#" className="hover:opacity-90">
        rocket
      </a>
    </nav>
  );
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="sm:scroll-smooth">
      <body
        className={clsx(
          inter.className,
          "min-h-screen bg-slate-50 dark:bg-black dark:text-white",
        )}
      >
        <header className="sticky top-0 z-10 bg-teal-700 text-white">
          <section className="mx-auto flex max-w-4xl items-center justify-between p-4">
            <a href="#hero-section" className="text-3xl font-medium">
              stroiman
            </a>
            <div>
              <button
                id="mobile-open"
                className="text-3xl focus:outline-none sm:hidden"
              >
                &#9776;
              </button>
              <Nav />
            </div>
          </section>
        </header>

        <main className="mx-auto max-w-4xl">{children}</main>
        <footer id="footer" className="bg-teal-800 text-xl text-white">
          <section className="mx-auto flex max-w-4xl flex-col p-4 sm:flex-row sm:justify-between">
            <address className="text-sm">
              <h2>Peter Strøiman ApS</h2>
              Email: <a href="mailto:info@stroiman.com">info@stroiman.com</a>
              <br />
            </address>
            <nav className="hidden flex-col gap-2 md:flex" aria-label="footer">
              <a href="#hero-section" className="hover:opacity-90">
                Back up
              </a>
            </nav>
          </section>
        </footer>
      </body>
    </html>
  );
}
