/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/H1bqdycYzLF
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'
import { Archivo } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function SkillsPage() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="space-y-4 text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Skills</h2>
          <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Explore the technical skills I've developed as a software developer.
          </p>
        </div>
        <div className="grid gap-6 mt-10 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
          <div className="flex flex-col items-center p-6 bg-background rounded-lg shadow-lg">
            <div className="bg-primary rounded-full p-3 mb-4">
              <CodeIcon className="w-6 h-6 text-primary-foreground" />
            </div>
            <h3 className="text-xl font-semibold">JavaScript</h3>
            <p className="text-muted-foreground text-center mt-2">
              Proficient in modern JavaScript, including ES6+ features and popular frameworks like React and Node.js.
            </p>
          </div>
          <div className="flex flex-col items-center p-6 bg-background rounded-lg shadow-lg">
            <div className="bg-primary rounded-full p-3 mb-4">
              <CpuIcon className="w-6 h-6 text-primary-foreground" />
            </div>
            <h3 className="text-xl font-semibold">Python</h3>
            <p className="text-muted-foreground text-center mt-2">
              Experienced in Python, with expertise in data analysis, machine learning, and backend development.
            </p>
          </div>
          <div className="flex flex-col items-center p-6 bg-background rounded-lg shadow-lg">
            <div className="bg-primary rounded-full p-3 mb-4">
              <DatabaseIcon className="w-6 h-6 text-primary-foreground" />
            </div>
            <h3 className="text-xl font-semibold">SQL</h3>
            <p className="text-muted-foreground text-center mt-2">
              Skilled in SQL, with experience in designing and optimizing relational databases.
            </p>
          </div>
          <div className="flex flex-col items-center p-6 bg-background rounded-lg shadow-lg">
            <div className="bg-primary rounded-full p-3 mb-4">
              <LayersIcon className="w-6 h-6 text-primary-foreground" />
            </div>
            <h3 className="text-xl font-semibold">React</h3>
            <p className="text-muted-foreground text-center mt-2">
              Proficient in building modern, responsive web applications using React and its ecosystem.
            </p>
          </div>
          <div className="flex flex-col items-center p-6 bg-background rounded-lg shadow-lg">
            <div className="bg-primary rounded-full p-3 mb-4">
              <CloudIcon className="w-6 h-6 text-primary-foreground" />
            </div>
            <h3 className="text-xl font-semibold">AWS</h3>
            <p className="text-muted-foreground text-center mt-2">
              Experienced in deploying and managing applications on AWS, including EC2, S3, and Lambda.
            </p>
          </div>
          <div className="flex flex-col items-center p-6 bg-background rounded-lg shadow-lg">
            <div className="bg-primary rounded-full p-3 mb-4">
              <GitBranchIcon className="w-6 h-6 text-primary-foreground" />
            </div>
            <h3 className="text-xl font-semibold">Git</h3>
            <p className="text-muted-foreground text-center mt-2">
              Proficient in version control using Git, with experience in collaborating on projects and resolving
              conflicts.
            </p>
          </div>
        </div>
      </div>
    </section>
  )
}

function CloudIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />
    </svg>
  )
}


function CodeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  )
}


function CpuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="16" height="16" x="4" y="4" rx="2" />
      <rect width="6" height="6" x="9" y="9" rx="1" />
      <path d="M15 2v2" />
      <path d="M15 20v2" />
      <path d="M2 15h2" />
      <path d="M2 9h2" />
      <path d="M20 15h2" />
      <path d="M20 9h2" />
      <path d="M9 2v2" />
      <path d="M9 20v2" />
    </svg>
  )
}


function DatabaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>
  )
}


function GitBranchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="6" x2="6" y1="3" y2="15" />
      <circle cx="18" cy="6" r="3" />
      <circle cx="6" cy="18" r="3" />
      <path d="M18 9a9 9 0 0 1-9 9" />
    </svg>
  )
}


function LayersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z" />
      <path d="m22 17.65-9.17 4.16a2 2 0 0 1-1.66 0L2 17.65" />
      <path d="m22 12.65-9.17 4.16a2 2 0 0 1-1.66 0L2 12.65" />
    </svg>
  )
}
