import { dir } from "i18next";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { clsx } from "clsx";
import Menu from "../ui/menu";
import Link from "next/link";
import { languages } from "../i18n/settings";

const inter = Inter({ subsets: ["latin"] });

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lng: string };
}>) {
  const { lng } = params;
  return (
    <html lang={lng} dir={dir(lng)} className="sm:scroll-smooth">
      <body
        className={clsx(
          inter.className,
          "min-h-screen bg-slate-50 dark:bg-black dark:text-white",
        )}
      >
        <Menu params={params} />

        <main className="mx-auto max-w-4xl">{children}</main>
        <footer id="footer" className="bg-teal-800 text-xl text-white">
          <section className="mx-auto flex max-w-4xl flex-col p-4 sm:flex-row sm:justify-between">
            <address className="text-sm">
              <h2>Peter Strøiman ApS</h2>
              Email: <a href="mailto:info@stroiman.com">info@stroiman.com</a>
              <br />
            </address>
            <nav className="hidden flex-col gap-2 md:flex" aria-label="footer">
              <Link href="#hero-section" className="hover:opacity-90">
                Back up
              </Link>
            </nav>
          </section>
        </footer>
      </body>
    </html>
  );
}
