import { dir } from "i18next";
import type { Metadata } from "next";
import { Inter, Source_Serif_4 } from "next/font/google";
import "../globals.css";
import { clsx } from "clsx";
import { languages } from "../i18n/settings";
import { Lang } from "../i18n";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });
const sourceSefif = Source_Serif_4({
  subsets: ["latin"],
  variable: "--source-serif",
});

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lng: Lang };
}>) {
  const { lng } = params;
  return (
    <html lang={lng} dir={dir(lng)} className="sm:scroll-smooth">
      <head>
        <title>Peter Strøiman - Freelance Software Developer</title>
      </head>
      <body
        className={clsx(
          inter.className,
          sourceSefif.className,

          "min-h-screen bg-slate-50 bg-gradient-to-br from-orange-100 to-slate-200 font-light dark:bg-black dark:from-orange-950 dark:to-slate-900 dark:text-white",
        )}
      >
        {children}
      </body>
    </html>
  );
}
